export const USER_PROFILE_ROUTE_ACCESS_ATTEMPT_CHARGE = 50;
export const USER_DELETE_ROUTE_ACCESS_ATTEMPT_CHARGE = 50;
export const USER_PASS_RESET_ROUTE_ACCESS_ATTEMPT_CHARGE = 50;
export const USER_WRONG_CREDENTIAL_ATTEMPT_CHARGE = 50;

export const CHARGE_FOR_SENDING_INVALID_DATA = 50;
export const PROTECTED_ROUTE_ACCESS_ATTEMPT_CHARGE = 50;
export const UNAUTHORIZED_ACCESS_ATTEMPT_CHARGE = 50;
